### ISSUE TITLE
library throw loader error when import in react cra

### ISSUE THREAD

**Issue by mmustafau** [sindresorhus/screenfull#197] opened 2021-11-17 07:22 UTC
hi,

I want to use this library with react-player library. 

At this official example,this package works fine. You can see [demo](https://cookpete.com/react-player/)

In my application it throws loaders error. 

```
./node_modules/screenfull/index.js 105:54
Module parse failed: Unexpected token (105:54)
File was processed with these loaders:
  ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   element: {
|     enumerable: true,
     get: () => document[nativeAPI.fullscreenElement] ?? undefined
|   },
|   isEnabled: {
```

package.json

```
 "react": "^16.13.1",
 "react-dom": "^16.13.1",
 "react-player": "^2.9.0",
 "react-router-dom": "^5.1.2",
 "redux": "^4.0.5",
 "redux-thunk": "^2.3.0",
 "react-scripts": "^4.0.3"

 "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
```

Thanks for the help

**Comment by sindresorhus** [comment] 2021-11-17 07:31
Duplicate of #195

**Closed by sindresorhus** 2021-11-17 07:32 UTC

**Comment by mmustafau** [comment] 2021-11-17 09:28
As a quick workaround,
You can downgrade screenfull version to 5.2.0.
In version 6.0.0. engine is higher than node v.14.
