### ISSUE TITLE
Failed to compile with error

### ISSUE THREAD

**Issue by signight** [sindresorhus/screenfull#198] opened 2021-11-23 09:02 UTC
ERROR  Failed to compile with 1 error                                                                                                                                                     下午4:36:51

 error  in ./node_modules/screenfull/index.js

Module parse failed: Unexpected token (55:42)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
|       for (const methodList of methodMap) {
>               const exitFullscreenMethod = methodList?.[1];
|               if (exitFullscreenMethod in document) {
|                       for (const [index, method] of methodList.entries()) {

Which loader should I need to install ？thx

**Comment by sindresorhus** [comment] 2021-11-23 09:30
Duplicate of #195

**Closed by sindresorhus** 2021-11-23 09:30 UTC
